### ISSUE TITLE
remove will not work

### ISSUE THREAD

**Issue by catalinoprea** [z4o4z/es6-store#3]
Hi,

The method remove will not work, you check if key is string without actually passing the key as argument to the `isKeyAString` method (line 207)

**Comment by z4o4z** [comment]
@catalinoprea Hi! Thanks for this issue, I'll fix it asap and try to add some tests for it!

**Comment by z4o4z** [comment]
@catalinoprea I just checked it and all looks good, I pass key to  `isKeyAString`.
https://github.com/z4o4z/es6-store/blob/master/src/Store.js#L207

**Comment by catalinoprea** [comment]
I have npm version, I didn't use git: https://www.npmjs.com/package/es6-store

**Comment by z4o4z** [comment]
looks really strange, I'll create new version for npm!

**Comment by z4o4z** [comment]
@catalinoprea fixed
